# Build CI Pipeline

name: DevelopCI_$(Year:yyyy).$(Month).$(DayOfMonth).$(Rev:r)    

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: 'Install .Net Core SDK'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: Assembly-Info-NetCore@2
  displayName: 'Update assembly info'
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: 'src/Tinyman/Tinyman.csproj'
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    FileVersionNumber: '$(Build.BuildNumber)'
    PackageVersion: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: true

- task: DotNetCoreCLI@2
  displayName: 'Build Tinyman .NET SDK'
  inputs:
    command: 'build'
    configuration: 'Release'
    projects: 'src/Tinyman/Tinyman.csproj'

- task: DotNetCoreCLI@2
  displayName: "Test Tinyman .NET SDK"
  inputs:
    command: test
    configuration: 'Release'
    projects: 'test/Tinyman.UnitTest/Tinyman.UnitTest.csproj'

- task: DotNetCoreCLI@2
  displayName: "Pack Tinyman .NET SDK Nuget package"
  inputs:
    command: 'pack'
    packagesToPack: 'src/Tinyman/Tinyman.csproj'
    nobuild: true
    versioningScheme: 'off' 