# Build CI Pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .Net Core SDK'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: DotNetCoreCLI@2
  displayName: 'Build Tinyman .NET SDK ($(buildConfiguration))'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: 'src/Tinyman/Tinyman.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Test Tinyman .NET SDK'
  inputs:
    command: test
    arguments: '--configuration $(buildConfiguration)'
    projects: 'test/Tinyman.UnitTest/Tinyman.UnitTest.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Package Tinyman .NET SDK'
  inputs:
    command: 'pack'
    configuration: '$(buildConfiguration)'
    packagesToPack: 'src/Tinyman/Tinyman.csproj'
    nobuild: true
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '0'
    minorVersion: '1'
    patchVersion: '0'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Tinyman .NET SDK'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'