# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: 'Install .Net Core SDK'
  inputs:
    packageType: 'sdk'
    version: '2.x'

- task: DotNetCoreCLI@2
  displayName: 'Build Tinyman .NET SDK'
  inputs:
    command: 'build'
    configuration: 'Release'
    projects: 'src/Tinyman/Tinyman.csproj'

- task: DotNetCoreCLI@2
  displayName: "Test Tinyman .NET SDK"
  inputs:
    command: test